### ISSUE TITLE
Cannot operate on a closed database

### ISSUE THREAD

**Issue by Nord1cWarr1or** [vadymfedorets/CatsvsDogs#2]
Воникла какая-то ошибка в питоне при выполнении таска, единоразово
```
Cats&Dogs | 2024-09-25 14:52:39 | INFO     | 145 - vadim_pyro | Joined to channel: catsdogs_community
Task exception was never retrieved
future: <Task finished name='Task-147' coro=<Client.handle_updates() done, defined at /home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/pyrogram/client.py:535> exception=ProgrammingError('Cannot operate on a closed database.')>
Traceback (most recent call last):
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/pyrogram/client.py", line 540, in handle_updates
await self.fetch_peers(updates.users),
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/pyrogram/client.py", line 531, in fetch_peers
await self.storage.update_peers(parsed_peers)
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/pyrogram/storage/sqlite_storage.py", line 129, in update_peers
self.conn.executemany(
sqlite3.ProgrammingError: Cannot operate on a closed database.
Cats&Dogs | 2024-09-25 14:52:39 | SUCCESS  | 175 - vadim_pyro | Task Join our community completed! | Reward: +300 FOOD
```

**Comment by vadymfedorets** [comment]
Если паралельно бота используешь с такой же сессией может выбивать, так же может быть ошибка пирограма, такое бывает. Проблема возникла только у тебя локально, так что не волнуйся, никуда дальше не идет, бан за это дать не могут.

**Comment by Nord1cWarr1or** [comment]
спасибо
