### ISSUE TITLE
ValueError: Peer id invalid: -1002165353586

### ISSUE THREAD

**Issue by Nord1cWarr1or** [vadymfedorets/CatsvsDogs#5]
```
Task exception was never retrieved
future: <Task finished name='Task-200' coro=<Client.handle_updates() done, defined at /home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/pyrogram/client.py:535> exception=ValueError('Peer id invalid: -1002165353586')>
Traceback (most recent call last):
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 62, in resolve_peer
return await self.storage.get_peer_by_id(peer_id)
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/pyrogram/storage/sqlite_storage.py", line 142, in get_peer_by_id
raise KeyError(f"ID not found: {peer_id}")
KeyError: 'ID not found: -1002165353586'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/pyrogram/client.py", line 569, in handle_updates
channel=await self.resolve_peer(utils.get_channel_id(channel_id)),
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/pyrogram/methods/advanced/resolve_peer.py", line 89, in resolve_peer
peer_type = utils.get_peer_type(peer_id)
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/pyrogram/utils.py", line 246, in get_peer_type
raise ValueError(f"Peer id invalid: {peer_id}")
ValueError: Peer id invalid: -1002165353586
```
Бот продолжил работать после этого

**Comment by vadymfedorets** [comment]
спуль ветку
