### ISSUE TITLE
ValueError: Tag "<html>" does not correspond to any known color directive

### ISSUE THREAD

**Issue by Nord1cWarr1or** [vadymfedorets/CatsvsDogs#6]
```
Traceback (most recent call last):
File "/home/wp/tgbots/CatsvsDogs/bot/core/tapper.py", line 123, in check_proxy
logger.info(f"{self.session_name} | Proxy IP: {ip}")
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/loguru/_logger.py", line 2044, in info
__self._log("INFO", False, __self._options, __message, args, kwargs)
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/loguru/_logger.py", line 2017, in _log
colored_message = Colorizer.prepare_simple_message(str(message))
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/loguru/_colorizer.py", line 368, in prepare_simple_message
parser.feed(string)
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/loguru/_colorizer.py", line 252, in feed
raise ValueError(
ValueError: Tag "<html>" does not correspond to any known color directive, make sure you did not misspelled it (or prepend '\' to escape it)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/wp/tgbots/CatsvsDogs/main.py", line 15, in <module>
asyncio.run(main())
File "/home/wp/.pyenv/versions/3.10.12/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/home/wp/.pyenv/versions/3.10.12/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/home/wp/tgbots/CatsvsDogs/main.py", line 10, in main
await process()
File "/home/wp/tgbots/CatsvsDogs/bot/utils/launcher.py", line 71, in process
await run_tasks(accounts=accounts)
File "/home/wp/tgbots/CatsvsDogs/bot/utils/launcher.py", line 83, in run_tasks
await asyncio.gather(*tasks)
File "/home/wp/tgbots/CatsvsDogs/bot/core/tapper.py", line 310, in run_tapper
await Tapper(tg_client=tg_client).run(user_agent=user_agent, proxy=proxy)
File "/home/wp/tgbots/CatsvsDogs/bot/core/tapper.py", line 258, in run
await self.check_proxy(http_client=http_client, proxy=proxy)
File "/home/wp/tgbots/CatsvsDogs/bot/core/tapper.py", line 125, in check_proxy
logger.error(f"{self.session_name} | Proxy: {proxy} | Error: {error}")
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/loguru/_logger.py", line 2056, in error
__self._log("ERROR", False, __self._options, __message, args, kwargs)
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/loguru/_logger.py", line 2017, in _log
colored_message = Colorizer.prepare_simple_message(str(message))
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/loguru/_colorizer.py", line 368, in prepare_simple_message
parser.feed(string)
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/loguru/_colorizer.py", line 252, in feed
raise ValueError(
ValueError: Tag "<html>" does not correspond to any known color directive, make sure you did not misspelled it (or prepend '\' to escape it)
```
Бот остановился после этого

**Comment by vadymfedorets** [comment]
спуль ветку, проблем быть не должно

**Comment by Nord1cWarr1or** [comment]
Окей, если опять будет, напишу. Спасибо

**Comment by Nord1cWarr1or** [comment]
Опять упал бот с той же ошибкой. 
```
Traceback (most recent call last):
File "/home/wp/tgbots/CatsvsDogs/bot/core/tapper.py", line 123, in check_proxy
logger.info(f"{self.session_name} | Proxy IP: {ip}")
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/loguru/_logger.py", line 2044, in info
__self._log("INFO", False, __self._options, __message, args, kwargs)
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/loguru/_logger.py", line 2017, in _log
colored_message = Colorizer.prepare_simple_message(str(message))
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/loguru/_colorizer.py", line 368, in prepare_simple_message
parser.feed(string)
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/loguru/_colorizer.py", line 252, in feed
raise ValueError(
ValueError: Tag "<html>" does not correspond to any known color directive, make sure you did not misspelled it (or prepend '\' to escape it)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/wp/tgbots/CatsvsDogs/main.py", line 15, in <module>
asyncio.run(main())
File "/home/wp/.pyenv/versions/3.10.12/lib/python3.10/asyncio/runners.py", line 44, in run
return loop.run_until_complete(main)
File "/home/wp/.pyenv/versions/3.10.12/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
return future.result()
File "/home/wp/tgbots/CatsvsDogs/main.py", line 10, in main
await process()
File "/home/wp/tgbots/CatsvsDogs/bot/utils/launcher.py", line 71, in process
await run_tasks(accounts=accounts)
File "/home/wp/tgbots/CatsvsDogs/bot/utils/launcher.py", line 83, in run_tasks
await asyncio.gather(*tasks)
File "/home/wp/tgbots/CatsvsDogs/bot/core/tapper.py", line 312, in run_tapper
await Tapper(tg_client=tg_client).run(user_agent=user_agent, proxy=proxy)
File "/home/wp/tgbots/CatsvsDogs/bot/core/tapper.py", line 260, in run
await self.check_proxy(http_client=http_client, proxy=proxy)
File "/home/wp/tgbots/CatsvsDogs/bot/core/tapper.py", line 125, in check_proxy
logger.error(f"{self.session_name} | Proxy: {proxy} | Error: {error}")
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/loguru/_logger.py", line 2056, in error
__self._log("ERROR", False, __self._options, __message, args, kwargs)
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/loguru/_logger.py", line 2017, in _log
colored_message = Colorizer.prepare_simple_message(str(message))
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/loguru/_colorizer.py", line 368, in prepare_simple_message
parser.feed(string)
File "/home/wp/tgbots/CatsvsDogs/venv/lib/python3.10/site-packages/loguru/_colorizer.py", line 252, in feed
raise ValueError(
ValueError: Tag "<html>" does not correspond to any known color directive, make sure you did not misspelled it (or prepend '\' to escape it)
```
Версия последняя.
```
(venv) wp@90ff2d773d3 ~/t/CatsvsDogs (master) [0|1]> git pull
Already up to date.
```

**Comment by dsadwqeqeasad** [comment]
у тебя прокси подохрительное для сайта с айпи чекером, оно такое выдает, если подозрительная активность

**Comment by Nord1cWarr1or** [comment]
> у тебя прокси подохрительное для сайта с айпи чекером, оно такое выдает, если подозрительная активность

Странно. Использую ещё нот пиксель твой же, там не падает бот, прокси те же самые.

**Comment by dsadwqeqeasad** [comment]
хз, не могу помочь, это ответ с сайта айпи чекера, можешь его отключить, если хочешь
